all_service_defaults:
  owner: "{{ admin.name }}"

traefik:
  name: traefik
  directory: "{{ docker_dir }}/traefik"
  domain: "traefik.pinyto.de"

portainer:
  name: portainer
  admin_user: "admin"
  directory: "{{ docker_dir }}/portainer"
  admin_password: "6sjGtgBr1EkX1EARfkxovKh5p"

watchtower:
  name: watchtower
  directory: "{{ docker_dir }}/watchtower"
  http_token: "6sjGtgBr1EkX1EARfkxovKh5p"
  telegram_bot_token: ""

autoheal:
  name: autoheal
  directory: "{{ docker_dir }}/autoheal"
  telegram_bot:
    enabled: false
    token: ""
    channel_id: ""