- name: apt install basic dependencies
  become: yes
  apt:
    update_cache: yes
    name:
      - ca-certificates
      - gnupg
      - lsb-release
      - python3
      - python3-pip
    state: latest

- name: Add docker GPG apt key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  when: ansible_os_family == 'Debian'

- name: Add docker official repository for Debian {{ ansible_distribution_release }}
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    state: present
  when: ansible_os_family == 'Debian'

- name: Update apt and install docker-ce
  become: yes
  apt:
    update_cache: yes
    name: docker-ce
    state: latest

- name: Add remote user to "docker" group
  become: yes
  user:
    name: "{{ admin.name }}"
    groups: "docker"
    append: yes

- name: Install docker python module
  pip:
    state: latest
    name:
      - docker
      - pyyaml
      - docker-compose
      - lxml

- name: Ensure {{ docker_dir }} exists
  file:
    path: "{{ docker_dir }}"
    state: directory
    owner: "{{ admin.name }}"
    group: "docker"
    mode: 0775