- name: Enable passwordless sudo for admin user {{ user.name }}
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^{{ user.name }}"
    line: "{{ user.name }} ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

- name: import ssh tasks
  import_tasks: ssh.yml

- name: Install apt packages
  apt:
    update_cache: yes
    name: "{{ basic_packages }}"
    state: present

- name: All packages installed.
  debug:
    msg: Packages have been successfully installed

- name: adding existing user '{{ user }}' to sudo group
  user:
    name: '{{ user.name }}'
    groups: sudo
    append: yes
